tasks:  
  example-task:
    repository: {repo_name}
    steps:
      - action: clone
        org: {org_name}
      
      - action: destroy
        file_path: 'config.yml'
        value: 'false'

      - action: commit_file
        auto_commit: 'true'
        branch: {branch_name}
        commit_msg: "Iniciando a execucao dos testes regressivos"

      - action: workflow_monitor
        workflow_name: "1 - ANALYTICS - Build and PR"
        show_workflow: 'true'
      
      - action: approve_pull_request
        source_branch: {branch_name}
        target_branch: develop

      - action: workflow_monitor
        workflow_name: "1 - FEAT - Build and PR"
        show_workflow: 'true'

      - action: approve_pull_request
        source_branch: {branch_name}
        target_branch: develop

      - action: workflow_monitor
        workflow_name: "2 - DEV - Build and Deploy"

      - action: approve_pull_request
        source_branch: develop
        target_branch: release/*

      - action: workflow_monitor
        workflow_name: "3 - HOM - Homologacao"


