tasks:
  v1.0-0.9.2:
    repository: repo1
    steps:
    - action: clone
      org: itau-corp
    - action: replace_file
      source_path: v1.0/0.9.2/config.yml
      target_path: ''
    - action: replace_dir
      source_path: v1.0/.github/workflows
      target_path: .github/workflows
    - action: destroy
      file_path: config.yml
      value: create
    - action: commit_file
      auto_commit: 'true'
      branch: analytics
      commit_msg: Iniciando a execucao dos testes regressivos
    - action: workflow_monitor
      show_workflow: 'true'
      workflow_name: 1 - ANALYTICS - Build and PR
